startEdit()

cd('/')
cmo.createJMSSystemResource('AnkiModule')
cd('/JMSSystemResources/AnkiModule')
set('Targets',jarray.array([ObjectName('com.bea:Name=AdminServerBAM,Type=Server')], ObjectName))
cmo.createSubDeployment('AnkiSubdeployment')
cd('/JMSSystemResources/AnkiModule/SubDeployments/AnkiSubdeployment')
set('Targets',jarray.array([ObjectName('com.bea:Name=BAMJMSServer,Type=JMSServer')], ObjectName))

cd('/JMSSystemResources/AnkiModule/JMSResource/AnkiModule')
cmo.createQueue('CurrentRace')
cd('/JMSSystemResources/AnkiModule/JMSResource/AnkiModule/Queues/CurrentRace')
cmo.setJNDIName('jms/anki/event/currentrace')
cmo.setSubDeploymentName('AnkiSubdeployment')
cd('/JMSSystemResources/AnkiModule/SubDeployments/AnkiSubdeployment')
set('Targets',jarray.array([ObjectName('com.bea:Name=BAMJMSServer,Type=JMSServer')], ObjectName))

cd('/JMSSystemResources/AnkiModule/JMSResource/AnkiModule')
cmo.createQueue('CurrentSpeed')
cd('/JMSSystemResources/AnkiModule/JMSResource/AnkiModule/Queues/CurrentSpeed')
cmo.setJNDIName('jms/anki/event/currentspeed')
cmo.setSubDeploymentName('AnkiSubdeployment')
cd('/JMSSystemResources/AnkiModule/SubDeployments/AnkiSubdeployment')
set('Targets',jarray.array([ObjectName('com.bea:Name=BAMJMSServer,Type=JMSServer')], ObjectName))

cd('/JMSSystemResources/AnkiModule/JMSResource/AnkiModule')
cmo.createQueue('DroneStatus')
cd('/JMSSystemResources/AnkiModule/JMSResource/AnkiModule/Queues/DroneStatus')
cmo.setJNDIName('jms/anki/event/dronestatus')
cmo.setSubDeploymentName('AnkiSubdeployment')
cd('/JMSSystemResources/AnkiModule/SubDeployments/AnkiSubdeployment')
set('Targets',jarray.array([ObjectName('com.bea:Name=BAMJMSServer,Type=JMSServer')], ObjectName))

cd('/JMSSystemResources/AnkiModule/JMSResource/AnkiModule')
cmo.createQueue('Lap')
cd('/JMSSystemResources/AnkiModule/JMSResource/AnkiModule/Queues/Lap')
cmo.setJNDIName('jms/anki/event/lap')
cmo.setSubDeploymentName('AnkiSubdeployment')
cd('/JMSSystemResources/AnkiModule/SubDeployments/AnkiSubdeployment')
set('Targets',jarray.array([ObjectName('com.bea:Name=BAMJMSServer,Type=JMSServer')], ObjectName))

cd('/JMSSystemResources/AnkiModule/JMSResource/AnkiModule')
cmo.createQueue('Offtrack')
cd('/JMSSystemResources/AnkiModule/JMSResource/AnkiModule/Queues/Offtrack')
cmo.setJNDIName('jms/anki/event/offtrack')
cmo.setSubDeploymentName('AnkiSubdeployment')
cd('/JMSSystemResources/AnkiModule/SubDeployments/AnkiSubdeployment')
set('Targets',jarray.array([ObjectName('com.bea:Name=BAMJMSServer,Type=JMSServer')], ObjectName))

cd('/JMSSystemResources/AnkiModule/JMSResource/AnkiModule')
cmo.createQueue('Speed')
cd('/JMSSystemResources/AnkiModule/JMSResource/AnkiModule/Queues/Speed')
cmo.setJNDIName('jms/anki/event/speed')
cmo.setSubDeploymentName('AnkiSubdeployment')
cd('/JMSSystemResources/AnkiModule/SubDeployments/AnkiSubdeployment')
set('Targets',jarray.array([ObjectName('com.bea:Name=BAMJMSServer,Type=JMSServer')], ObjectName))

activate()
